apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <!-- 
        It would have been nicer to use a separate workspace for this but it seems 
        the Maven task does not allow others than the ones passed in as
        'source' and 'maven-settings'. See if putting them in here will help with
        caching of dependencies
      -->
      <localRepository>/workspace/source/.maven-repo</localRepository>
    </settings>
